const GET_ALL_POSTS = "GET_ALL_POSTS";
const GET_ALL_POSTS_STARTED = "GET_ALL_POSTS_STARTED";
const GET_ALL_POSTS_SUCCESS = "GET_ALL_POSTS_SUCCESS";
const GET_ALL_POSTS_FAILED = "GET_ALL_POSTS_FAILED";

const POST_COMMENT_BY_POST_ID = "POST_COMMENT_BY_POST_ID";

const GET_CURRENT_USER = "GET_CURRENT_USER";

export {
  GET_ALL_POSTS,
  GET_ALL_POSTS_STARTED,
  GET_ALL_POSTS_SUCCESS,
  GET_ALL_POSTS_FAILED,
  POST_COMMENT_BY_POST_ID,
  GET_CURRENT_USER,
};
