const GET_ALL_POSTS = "GET_ALL_POSTS";
const GET_ALL_POSTS_STARTED = "GET_ALL_POSTS_STARTED";
const GET_ALL_POSTS_SUCCESS = "GET_ALL_POSTS_SUCCESS";
const GET_ALL_POSTS_FAILED = "GET_ALL_POSTS_FAILED";

const GET_CURRENT_USER = "GET_CURRENT_USER";

const CREATE_NEW_COMMENT = "CREATE_NEW_COMMENT";
export {
  GET_ALL_POSTS,
  GET_ALL_POSTS_STARTED,
  GET_ALL_POSTS_SUCCESS,
  GET_ALL_POSTS_FAILED,
  GET_CURRENT_USER,
  CREATE_NEW_COMMENT,
};
