const GET_ALL_POSTS = "GET_ALL_POSTS";
const GET_ALL_POSTS_STARTED = "GET_ALL_POSTS_STARTED";
const GET_ALL_POSTS_SUCCESS = "GET_ALL_POSTS_SUCCESS";
const GET_ALL_POSTS_FAILED = "GET_ALL_POSTS_FAILED";
const OPEN_CREATE_POST_MODAL = "OPEN_CREATE_POST_MODAL";
const CLOSE_CREATE_POST_MODAL = "CLOSE_CREATE_POST_MODAL";
const GET_CURRENT_USER = "GET_CURRENT_USER";

const CREATE_NEW_COMMENT_REQUESTED = "CREATE_NEW_COMMENT_REQUESTED";
const CREATE_NEW_COMMENT_SUCCESSED = "CREATE_NEW_COMMENT_SUCCESSED";
const CREATE_NEW_COMMENT_FAILED = "CREATE_NEW_COMMENT_FAILED";

export {
  OPEN_CREATE_POST_MODAL,
  CLOSE_CREATE_POST_MODAL,
  GET_ALL_POSTS,
  GET_ALL_POSTS_STARTED,
  GET_ALL_POSTS_SUCCESS,
  GET_ALL_POSTS_FAILED,
  GET_CURRENT_USER,
  CREATE_NEW_COMMENT_REQUESTED,
  CREATE_NEW_COMMENT_SUCCESSED,
  CREATE_NEW_COMMENT_FAILED,
};
